### PR TITLE
Galal-bio.md

### PR DESCRIPTION
**Pull request by galalkoro98**
### General Checks

- [ ] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work

### CODE REVIEW

**Comment by inna9Z** [comment]
@galalkoro98 good job, looks nice ) if you don't want any changes in your MD file, I will do a review. Let me know)

**Comment by galalkoro98** [comment]
@inna9Z  you can review and mege, thanks

**Review by inna9Z — COMMENTED** [review]
Good job )

**Comment by inna9Z** [comment]
@galalkoro98 one remark, pull request issue we don’t need to add to the projects board, can you remove ) thanks  
@yildiztugbaif I am wrong, correct me, please )

**Comment by yildiztugba** [comment]
Yes, as the coaches mentioned it last Sunday, we agreed that nobody will add a pr to the project board.

**Pull request merged**
